---
- hosts: "localhost"
  environment:
    http_proxy:  ""
    https_proxy: ""
    HTTP_PROXY:  ""
    HTTPS_PROXY: ""
  vars_files:
  - vars/main.yaml
  tasks:
    - name: Prepara a descrição de violação de política
      set_fact:
        violation_short_description: >
          {%- if snow_short_description is defined -%}
          {{ snow_short_description }}
          {%- else -%}
          Violação da política {{ policy_name }} no RHACM
          {% endif %}
          [acm-policy: {{ policy_namespace }}/{{ policy_name }}]
        violation_description: |
          {%- if snow_description is defined -%}
          {{ snow_description }}
          {%- else -%}
          A política {{ policy_namespace }}/{{ policy_name }} foi violada para os seguintes clusters:
          {% for key, value in policy_violations.items() %}

          Cluster: {{ key }}
          Violação: {{ value.violation_message }}
          {% endfor %}

          Mais detalhes sobre a violação desta política podem ser encontrados no console do RHACM em https://{{ hub_cluster }}

          {% if snow_description_complement is defined %}
          {{ snow_description_complement }}
          {% endif %}
          {%- endif -%}
    - name: Print Short Description
      ansible.builtin.debug:
        msg: "{{ violation_short_description }}"
    - name: Print Description
      ansible.builtin.debug:
        msg: "{{ violation_description }}"
